// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kidx45/Debter/internal/port/outbound (interfaces: AccountRepository)

package mockrepository

import (
	context "context"
	reflect "reflect"

	postgres "github.com/kidx45/Debter/internal/adapter/outbound/postgres"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountRepository is a mock of AccountRepository interface.
type MockAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepositoryMockRecorder
	isgomock struct{}
}

// MockAccountRepositoryMockRecorder is the mock recorder for MockAccountRepository.
type MockAccountRepositoryMockRecorder struct {
	mock *MockAccountRepository
}

// NewMockAccountRepository creates a new mock instance.
func NewMockAccountRepository(ctrl *gomock.Controller) *MockAccountRepository {
	mock := &MockAccountRepository{ctrl: ctrl}
	mock.recorder = &MockAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepository) EXPECT() *MockAccountRepositoryMockRecorder {
	return m.recorder
}

// GetAccountsByUserId mocks base method.
func (m *MockAccountRepository) GetAccountsByUserId(ctx context.Context, userID int64) ([]postgres.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountsByUserId", ctx, userID)
	ret0, _ := ret[0].([]postgres.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountsByUserId indicates an expected call of GetAccountsByUserId.
func (mr *MockAccountRepositoryMockRecorder) GetAccountsByUserId(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountsByUserId", reflect.TypeOf((*MockAccountRepository)(nil).GetAccountsByUserId), ctx, userID)
}
