// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kidx45/Debter/internal/port/outbound (interfaces: EntryRepository)
//
// Generated by this command:
//
//	mockgen -package=mockrepository -destination ./internal/test/mock/repository/mock_entry.go github.com/kidx45/Debter/internal/port/outbound EntryRepository
//

// Package mockrepository is a generated GoMock package.
package mockrepository

import (
	context "context"
	reflect "reflect"

	db "github.com/kidx45/Debter/internal/adapter/outbound/postgres"
	gomock "go.uber.org/mock/gomock"
)

// MockEntryRepository is a mock of EntryRepository interface.
type MockEntryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEntryRepositoryMockRecorder
	isgomock struct{}
}

// MockEntryRepositoryMockRecorder is the mock recorder for MockEntryRepository.
type MockEntryRepositoryMockRecorder struct {
	mock *MockEntryRepository
}

// NewMockEntryRepository creates a new mock instance.
func NewMockEntryRepository(ctrl *gomock.Controller) *MockEntryRepository {
	mock := &MockEntryRepository{ctrl: ctrl}
	mock.recorder = &MockEntryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntryRepository) EXPECT() *MockEntryRepositoryMockRecorder {
	return m.recorder
}

// FilterEntriesByDate mocks base method.
func (m *MockEntryRepository) FilterEntriesByDate(ctx context.Context, arg db.FilterEntriesByDateParams) ([]db.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterEntriesByDate", ctx, arg)
	ret0, _ := ret[0].([]db.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterEntriesByDate indicates an expected call of FilterEntriesByDate.
func (mr *MockEntryRepositoryMockRecorder) FilterEntriesByDate(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterEntriesByDate", reflect.TypeOf((*MockEntryRepository)(nil).FilterEntriesByDate), ctx, arg)
}

// GetEntriesByAccountId mocks base method.
func (m *MockEntryRepository) GetEntriesByAccountId(ctx context.Context, arg db.GetEntriesByAccountIdParams) ([]db.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntriesByAccountId", ctx, arg)
	ret0, _ := ret[0].([]db.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntriesByAccountId indicates an expected call of GetEntriesByAccountId.
func (mr *MockEntryRepositoryMockRecorder) GetEntriesByAccountId(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntriesByAccountId", reflect.TypeOf((*MockEntryRepository)(nil).GetEntriesByAccountId), ctx, arg)
}

// GetEntriesByCategoryAndType mocks base method.
func (m *MockEntryRepository) GetEntriesByCategoryAndType(ctx context.Context, arg db.GetEntriesByCategoryAndTypeParams) ([]db.GetEntriesByCategoryAndTypeRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntriesByCategoryAndType", ctx, arg)
	ret0, _ := ret[0].([]db.GetEntriesByCategoryAndTypeRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntriesByCategoryAndType indicates an expected call of GetEntriesByCategoryAndType.
func (mr *MockEntryRepositoryMockRecorder) GetEntriesByCategoryAndType(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntriesByCategoryAndType", reflect.TypeOf((*MockEntryRepository)(nil).GetEntriesByCategoryAndType), ctx, arg)
}
