// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kidx45/Debter/internal/port/outbound (interfaces: EntryRepository)
//
// Generated by this command:
//
//	mockgen -package=mockrepository -destination ./internal/test/mock/repository/mock_entry.go github.com/kidx45/Debter/internal/port/outbound EntryRepository
//

// Package mockrepository is a generated GoMock package.
package mockrepository

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/kidx45/Debter/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockEntryRepository is a mock of EntryRepository interface.
type MockEntryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEntryRepositoryMockRecorder
	isgomock struct{}
}

// MockEntryRepositoryMockRecorder is the mock recorder for MockEntryRepository.
type MockEntryRepositoryMockRecorder struct {
	mock *MockEntryRepository
}

// NewMockEntryRepository creates a new mock instance.
func NewMockEntryRepository(ctrl *gomock.Controller) *MockEntryRepository {
	mock := &MockEntryRepository{ctrl: ctrl}
	mock.recorder = &MockEntryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntryRepository) EXPECT() *MockEntryRepositoryMockRecorder {
	return m.recorder
}

// CreateEntry mocks base method.
func (m *MockEntryRepository) CreateEntry(ctx context.Context, accountID, userID, amount int64, entryType, category string) (domain.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEntry", ctx, accountID, userID, amount, entryType, category)
	ret0, _ := ret[0].(domain.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEntry indicates an expected call of CreateEntry.
func (mr *MockEntryRepositoryMockRecorder) CreateEntry(ctx, accountID, userID, amount, entryType, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEntry", reflect.TypeOf((*MockEntryRepository)(nil).CreateEntry), ctx, accountID, userID, amount, entryType, category)
}

// FilterEntriesByDate mocks base method.
func (m *MockEntryRepository) FilterEntriesByDate(ctx context.Context, accountID, userID int64, from, to time.Time) ([]domain.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterEntriesByDate", ctx, accountID, userID, from, to)
	ret0, _ := ret[0].([]domain.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterEntriesByDate indicates an expected call of FilterEntriesByDate.
func (mr *MockEntryRepositoryMockRecorder) FilterEntriesByDate(ctx, accountID, userID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterEntriesByDate", reflect.TypeOf((*MockEntryRepository)(nil).FilterEntriesByDate), ctx, accountID, userID, from, to)
}

// GetEntriesByAccountId mocks base method.
func (m *MockEntryRepository) GetEntriesByAccountId(ctx context.Context, accountID, userID int64) ([]domain.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntriesByAccountId", ctx, accountID, userID)
	ret0, _ := ret[0].([]domain.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntriesByAccountId indicates an expected call of GetEntriesByAccountId.
func (mr *MockEntryRepositoryMockRecorder) GetEntriesByAccountId(ctx, accountID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntriesByAccountId", reflect.TypeOf((*MockEntryRepository)(nil).GetEntriesByAccountId), ctx, accountID, userID)
}

// GetEntriesByCategoryAndType mocks base method.
func (m *MockEntryRepository) GetEntriesByCategoryAndType(ctx context.Context, accountID, userID int64, entryType string) ([]domain.CategorySummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntriesByCategoryAndType", ctx, accountID, userID, entryType)
	ret0, _ := ret[0].([]domain.CategorySummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntriesByCategoryAndType indicates an expected call of GetEntriesByCategoryAndType.
func (mr *MockEntryRepositoryMockRecorder) GetEntriesByCategoryAndType(ctx, accountID, userID, entryType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntriesByCategoryAndType", reflect.TypeOf((*MockEntryRepository)(nil).GetEntriesByCategoryAndType), ctx, accountID, userID, entryType)
}

// Transfer mocks base method.
func (m *MockEntryRepository) Transfer(ctx context.Context, fromAccountID, toAccountID, userID, amount int64, entryType, category string) (domain.Entry, domain.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transfer", ctx, fromAccountID, toAccountID, userID, amount, entryType, category)
	ret0, _ := ret[0].(domain.Entry)
	ret1, _ := ret[1].(domain.Entry)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Transfer indicates an expected call of Transfer.
func (mr *MockEntryRepositoryMockRecorder) Transfer(ctx, fromAccountID, toAccountID, userID, amount, entryType, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transfer", reflect.TypeOf((*MockEntryRepository)(nil).Transfer), ctx, fromAccountID, toAccountID, userID, amount, entryType, category)
}
