// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kidx45/Debter/internal/port/outbound (interfaces: UserRepository)

package mockrepository

import (
	context "context"
	reflect "reflect"

	postgres "github.com/kidx45/Debter/internal/adapter/outbound/postgres"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserRepository) CreateUser(ctx context.Context, arg postgres.CreateUserParams) (postgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(postgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepository)(nil).CreateUser), ctx, arg)
}

// DeleteUserByUsername mocks base method.
func (m *MockUserRepository) DeleteUserByUsername(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserByUsername", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserByUsername indicates an expected call of DeleteUserByUsername.
func (mr *MockUserRepositoryMockRecorder) DeleteUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserByUsername", reflect.TypeOf((*MockUserRepository)(nil).DeleteUserByUsername), ctx, username)
}

// GetUserByUsername mocks base method.
func (m *MockUserRepository) GetUserByUsername(ctx context.Context, username string) (postgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(postgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockUserRepositoryMockRecorder) GetUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockUserRepository)(nil).GetUserByUsername), ctx, username)
}

// UpdateFullNameByUsername mocks base method.
func (m *MockUserRepository) UpdateFullNameByUsername(ctx context.Context, arg postgres.UpdateFullNameByUsernameParams) (postgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFullNameByUsername", ctx, arg)
	ret0, _ := ret[0].(postgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFullNameByUsername indicates an expected call of UpdateFullNameByUsername.
func (mr *MockUserRepositoryMockRecorder) UpdateFullNameByUsername(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFullNameByUsername", reflect.TypeOf((*MockUserRepository)(nil).UpdateFullNameByUsername), ctx, arg)
}

// UpdateUserNameByUsername mocks base method.
func (m *MockUserRepository) UpdateUserNameByUsername(ctx context.Context, arg postgres.UpdateUserNameByUsernameParams) (postgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserNameByUsername", ctx, arg)
	ret0, _ := ret[0].(postgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserNameByUsername indicates an expected call of UpdateUserNameByUsername.
func (mr *MockUserRepositoryMockRecorder) UpdateUserNameByUsername(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserNameByUsername", reflect.TypeOf((*MockUserRepository)(nil).UpdateUserNameByUsername), ctx, arg)
}
