// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kidx45/Debter/internal/port/outbound (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -package=mockrepository -destination ./internal/test/mock/repository/mock.go github.com/kidx45/Debter/internal/port/outbound Repository
//

// Package mockrepository is a generated GoMock package.
package mockrepository

import (
	context "context"
	reflect "reflect"

	postgres "github.com/kidx45/Debter/internal/adapter/outbound/postgres"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockRepository) CreateUser(ctx context.Context, arg postgres.CreateUserParams) (postgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(postgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockRepositoryMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockRepository)(nil).CreateUser), ctx, arg)
}

// DeleteUserByUsername mocks base method.
func (m *MockRepository) DeleteUserByUsername(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserByUsername", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserByUsername indicates an expected call of DeleteUserByUsername.
func (mr *MockRepositoryMockRecorder) DeleteUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserByUsername", reflect.TypeOf((*MockRepository)(nil).DeleteUserByUsername), ctx, username)
}

// FilterEntriesByDate mocks base method.
func (m *MockRepository) FilterEntriesByDate(ctx context.Context, arg postgres.FilterEntriesByDateParams) ([]postgres.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterEntriesByDate", ctx, arg)
	ret0, _ := ret[0].([]postgres.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterEntriesByDate indicates an expected call of FilterEntriesByDate.
func (mr *MockRepositoryMockRecorder) FilterEntriesByDate(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterEntriesByDate", reflect.TypeOf((*MockRepository)(nil).FilterEntriesByDate), ctx, arg)
}

// GetAccountsByUserId mocks base method.
func (m *MockRepository) GetAccountsByUserId(ctx context.Context, userID int64) ([]postgres.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountsByUserId", ctx, userID)
	ret0, _ := ret[0].([]postgres.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountsByUserId indicates an expected call of GetAccountsByUserId.
func (mr *MockRepositoryMockRecorder) GetAccountsByUserId(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountsByUserId", reflect.TypeOf((*MockRepository)(nil).GetAccountsByUserId), ctx, userID)
}

// GetEntriesByAccountId mocks base method.
func (m *MockRepository) GetEntriesByAccountId(ctx context.Context, accountID int64) ([]postgres.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntriesByAccountId", ctx, accountID)
	ret0, _ := ret[0].([]postgres.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntriesByAccountId indicates an expected call of GetEntriesByAccountId.
func (mr *MockRepositoryMockRecorder) GetEntriesByAccountId(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntriesByAccountId", reflect.TypeOf((*MockRepository)(nil).GetEntriesByAccountId), ctx, accountID)
}

// GetEntriesByCategoryAndType mocks base method.
func (m *MockRepository) GetEntriesByCategoryAndType(ctx context.Context, arg postgres.GetEntriesByCategoryAndTypeParams) ([]postgres.GetEntriesByCategoryAndTypeRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntriesByCategoryAndType", ctx, arg)
	ret0, _ := ret[0].([]postgres.GetEntriesByCategoryAndTypeRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntriesByCategoryAndType indicates an expected call of GetEntriesByCategoryAndType.
func (mr *MockRepositoryMockRecorder) GetEntriesByCategoryAndType(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntriesByCategoryAndType", reflect.TypeOf((*MockRepository)(nil).GetEntriesByCategoryAndType), ctx, arg)
}

// GetUserByUsername mocks base method.
func (m *MockRepository) GetUserByUsername(ctx context.Context, username string) (postgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(postgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockRepositoryMockRecorder) GetUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockRepository)(nil).GetUserByUsername), ctx, username)
}

// UpdateFullNameByUsername mocks base method.
func (m *MockRepository) UpdateFullNameByUsername(ctx context.Context, arg postgres.UpdateFullNameByUsernameParams) (postgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFullNameByUsername", ctx, arg)
	ret0, _ := ret[0].(postgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFullNameByUsername indicates an expected call of UpdateFullNameByUsername.
func (mr *MockRepositoryMockRecorder) UpdateFullNameByUsername(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFullNameByUsername", reflect.TypeOf((*MockRepository)(nil).UpdateFullNameByUsername), ctx, arg)
}

// UpdateUserNameByUsername mocks base method.
func (m *MockRepository) UpdateUserNameByUsername(ctx context.Context, arg postgres.UpdateUserNameByUsernameParams) (postgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserNameByUsername", ctx, arg)
	ret0, _ := ret[0].(postgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserNameByUsername indicates an expected call of UpdateUserNameByUsername.
func (mr *MockRepositoryMockRecorder) UpdateUserNameByUsername(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserNameByUsername", reflect.TypeOf((*MockRepository)(nil).UpdateUserNameByUsername), ctx, arg)
}
