// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kidx45/Debter/internal/port/outbound (interfaces: SessionRepository)
//
// Generated by this command:
//
//	mockgen -package=mockrepository -destination ./internal/test/mock/repository/mock_session.go github.com/kidx45/Debter/internal/port/outbound SessionRepository
//

// Package mockrepository is a generated GoMock package.
package mockrepository

import (
	context "context"
	reflect "reflect"

	db "github.com/kidx45/Debter/internal/adapter/outbound/postgres"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockSessionRepository) CreateSession(ctx context.Context, arg db.CreateSessionParams) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, arg)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockSessionRepositoryMockRecorder) CreateSession(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockSessionRepository)(nil).CreateSession), ctx, arg)
}

// GetSessionByRefreshToken mocks base method.
func (m *MockSessionRepository) GetSessionByRefreshToken(ctx context.Context, refreshToken string) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByRefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByRefreshToken indicates an expected call of GetSessionByRefreshToken.
func (mr *MockSessionRepositoryMockRecorder) GetSessionByRefreshToken(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByRefreshToken", reflect.TypeOf((*MockSessionRepository)(nil).GetSessionByRefreshToken), ctx, refreshToken)
}

// UpdateSessionRefreshToken mocks base method.
func (m *MockSessionRepository) UpdateSessionRefreshToken(ctx context.Context, arg db.UpdateSessionRefreshTokenParams) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionRefreshToken", ctx, arg)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSessionRefreshToken indicates an expected call of UpdateSessionRefreshToken.
func (mr *MockSessionRepositoryMockRecorder) UpdateSessionRefreshToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionRefreshToken", reflect.TypeOf((*MockSessionRepository)(nil).UpdateSessionRefreshToken), ctx, arg)
}
