apiVersion: apps/v1
kind: Deployment
metadata:
  name: debter-api
  labels:
    app: debter-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: debter-api
  template:
    metadata:
      labels:
        app: debter-api
    spec:
      containers:
        - name: debter-api
          image: mrknixt/debter:1.1 # tags will cause issue so always place one even if it is :latest
          ports:
            - containerPort: 8080
          env:
            - name: GIN_MODE
              value: "release"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: debter-secrets
                  key: DB_URL
            - name: DB_DRIVER_NAME
              valueFrom:
                secretKeyRef:
                  name: debter-secrets
                  key: DB_DRIVER_NAME
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: debter-secrets
                  key: PORT
            - name: TOKEN_SYMMETRIC_KEY
              valueFrom:
                secretKeyRef:
                  name: debter-secrets
                  key: TOKEN_SYMMETRIC_KEY
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz 
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20