apiVersion: v1
kind: Service
metadata:
  name: debter-api-service
  labels:
    app: debter-api
spec:
  selector:
    app: debter-api
  ports:
    - protocol: TCP
      port: 8080 # Service port
      targetPort: 8080 # Container port
  type: NodePort # change to LoadBalancer if running in cloud