// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"
)

const getAccountsByUserId = `-- name: GetAccountsByUserId :many
SELECT id, user_id, account_type, account_number, created_at FROM accounts
WHERE user_id = $1 ORDER BY account_type ASC
`

func (q *Queries) GetAccountsByUserId(ctx context.Context, userID int64) ([]Account, error) {
	rows, err := q.query(ctx, q.getAccountsByUserIdStmt, getAccountsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountType,
			&i.AccountNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
