// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package db

import (
	"context"
	"time"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (account_id, amount, type, category)
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, amount, type, category, created_at
`

type CreateEntryParams struct {
	AccountID int64  `json:"accountId"`
	Amount    int64  `json:"amount"`
	Type      string `json:"type"`
	Category  string `json:"category"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.queryRow(ctx, q.createEntryStmt, createEntry,
		arg.AccountID,
		arg.Amount,
		arg.Type,
		arg.Category,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Type,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const filterEntriesByDate = `-- name: FilterEntriesByDate :many
SELECT e.id, e.account_id, e.amount, e.type, e.category, e.created_at FROM entries e
JOIN accounts a ON a.id = e.account_id
WHERE e.account_id = $1 AND a.user_id = $2
AND e.created_at >= $3 AND e.created_at <= $4
ORDER BY e.created_at DESC
`

type FilterEntriesByDateParams struct {
	AccountID   int64     `json:"accountId"`
	UserID      int64     `json:"userId"`
	CreatedAt   time.Time `json:"createdAt"`
	CreatedAt_2 time.Time `json:"createdAt2"`
}

func (q *Queries) FilterEntriesByDate(ctx context.Context, arg FilterEntriesByDateParams) ([]Entry, error) {
	rows, err := q.query(ctx, q.filterEntriesByDateStmt, filterEntriesByDate,
		arg.AccountID,
		arg.UserID,
		arg.CreatedAt,
		arg.CreatedAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Type,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntriesByAccountId = `-- name: GetEntriesByAccountId :many
SELECT e.id, e.account_id, e.amount, e.type, e.category, e.created_at FROM entries e
JOIN accounts a ON a.id = e.account_id
WHERE e.account_id = $1 AND a.user_id = $2
ORDER BY e.created_at DESC
`

type GetEntriesByAccountIdParams struct {
	AccountID int64 `json:"accountId"`
	UserID    int64 `json:"userId"`
}

func (q *Queries) GetEntriesByAccountId(ctx context.Context, arg GetEntriesByAccountIdParams) ([]Entry, error) {
	rows, err := q.query(ctx, q.getEntriesByAccountIdStmt, getEntriesByAccountId, arg.AccountID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Type,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntriesByCategoryAndType = `-- name: GetEntriesByCategoryAndType :many
SELECT e.category, SUM(e.amount) AS total
FROM entries e
JOIN accounts a ON a.id = e.account_id
WHERE e.account_id = $1 AND a.user_id = $2
AND e.type = $3
GROUP BY e.category ORDER BY e.category DESC
`

type GetEntriesByCategoryAndTypeParams struct {
	AccountID int64  `json:"accountId"`
	UserID    int64  `json:"userId"`
	Type      string `json:"type"`
}

type GetEntriesByCategoryAndTypeRow struct {
	Category string `json:"category"`
	Total    int64  `json:"total"`
}

func (q *Queries) GetEntriesByCategoryAndType(ctx context.Context, arg GetEntriesByCategoryAndTypeParams) ([]GetEntriesByCategoryAndTypeRow, error) {
	rows, err := q.query(ctx, q.getEntriesByCategoryAndTypeStmt, getEntriesByCategoryAndType, arg.AccountID, arg.UserID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntriesByCategoryAndTypeRow
	for rows.Next() {
		var i GetEntriesByCategoryAndTypeRow
		if err := rows.Scan(&i.Category, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
