// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Account struct {
	ID            int64     `json:"id"`
	UserID        int64     `json:"userId"`
	AccountType   string    `json:"accountType"`
	AccountNumber int64     `json:"accountNumber"`
	CreatedAt     time.Time `json:"createdAt"`
	Balance       int64     `json:"balance"`
}

type Entry struct {
	ID        int64     `json:"id"`
	AccountID int64     `json:"accountId"`
	Amount    int64     `json:"amount"`
	Type      string    `json:"type"`
	Category  string    `json:"category"`
	CreatedAt time.Time `json:"createdAt"`
}

type Session struct {
	ID           int64     `json:"id"`
	UserID       int64     `json:"userId"`
	RefreshToken string    `json:"refreshToken"`
	UserAgent    string    `json:"userAgent"`
	ClientIp     string    `json:"clientIp"`
	IsBlocked    bool      `json:"isBlocked"`
	ExpiresAt    time.Time `json:"expiresAt"`
	CreatedAt    time.Time `json:"createdAt"`
}

type User struct {
	ID             int64     `json:"id"`
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashedPassword"`
	FullName       string    `json:"fullName"`
	Email          string    `json:"email"`
	CreatedAt      time.Time `json:"createdAt"`
}
