// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUserByUsername(ctx context.Context, username string) error
	FilterEntriesByDate(ctx context.Context, arg FilterEntriesByDateParams) ([]Entry, error)
	GetAccountsByUserId(ctx context.Context, userID int64) ([]Account, error)
	GetEntriesByAccountId(ctx context.Context, accountID int64) ([]Entry, error)
	GetEntriesByCategoryAndType(ctx context.Context, arg GetEntriesByCategoryAndTypeParams) ([]GetEntriesByCategoryAndTypeRow, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	UpdateFullNameByUsername(ctx context.Context, arg UpdateFullNameByUsernameParams) (User, error)
	UpdateUserNameByUsername(ctx context.Context, arg UpdateUserNameByUsernameParams) (User, error)
}

var _ Querier = (*Queries)(nil)
