// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteUserByUsernameStmt, err = db.PrepareContext(ctx, deleteUserByUsername); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUserByUsername: %w", err)
	}
	if q.filterEntriesByDateStmt, err = db.PrepareContext(ctx, filterEntriesByDate); err != nil {
		return nil, fmt.Errorf("error preparing query FilterEntriesByDate: %w", err)
	}
	if q.getAccountsByUserIdStmt, err = db.PrepareContext(ctx, getAccountsByUserId); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccountsByUserId: %w", err)
	}
	if q.getEntriesByAccountIdStmt, err = db.PrepareContext(ctx, getEntriesByAccountId); err != nil {
		return nil, fmt.Errorf("error preparing query GetEntriesByAccountId: %w", err)
	}
	if q.getEntriesByCategoryAndTypeStmt, err = db.PrepareContext(ctx, getEntriesByCategoryAndType); err != nil {
		return nil, fmt.Errorf("error preparing query GetEntriesByCategoryAndType: %w", err)
	}
	if q.getUserByUsernameStmt, err = db.PrepareContext(ctx, getUserByUsername); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByUsername: %w", err)
	}
	if q.updateUserNameByUsernameStmt, err = db.PrepareContext(ctx, updateUserNameByUsername); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserNameByUsername: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteUserByUsernameStmt != nil {
		if cerr := q.deleteUserByUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserByUsernameStmt: %w", cerr)
		}
	}
	if q.filterEntriesByDateStmt != nil {
		if cerr := q.filterEntriesByDateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing filterEntriesByDateStmt: %w", cerr)
		}
	}
	if q.getAccountsByUserIdStmt != nil {
		if cerr := q.getAccountsByUserIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountsByUserIdStmt: %w", cerr)
		}
	}
	if q.getEntriesByAccountIdStmt != nil {
		if cerr := q.getEntriesByAccountIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEntriesByAccountIdStmt: %w", cerr)
		}
	}
	if q.getEntriesByCategoryAndTypeStmt != nil {
		if cerr := q.getEntriesByCategoryAndTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEntriesByCategoryAndTypeStmt: %w", cerr)
		}
	}
	if q.getUserByUsernameStmt != nil {
		if cerr := q.getUserByUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByUsernameStmt: %w", cerr)
		}
	}
	if q.updateUserNameByUsernameStmt != nil {
		if cerr := q.updateUserNameByUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserNameByUsernameStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                              DBTX
	tx                              *sql.Tx
	createUserStmt                  *sql.Stmt
	deleteUserByUsernameStmt        *sql.Stmt
	filterEntriesByDateStmt         *sql.Stmt
	getAccountsByUserIdStmt         *sql.Stmt
	getEntriesByAccountIdStmt       *sql.Stmt
	getEntriesByCategoryAndTypeStmt *sql.Stmt
	getUserByUsernameStmt           *sql.Stmt
	updateUserNameByUsernameStmt    *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                              tx,
		tx:                              tx,
		createUserStmt:                  q.createUserStmt,
		deleteUserByUsernameStmt:        q.deleteUserByUsernameStmt,
		filterEntriesByDateStmt:         q.filterEntriesByDateStmt,
		getAccountsByUserIdStmt:         q.getAccountsByUserIdStmt,
		getEntriesByAccountIdStmt:       q.getEntriesByAccountIdStmt,
		getEntriesByCategoryAndTypeStmt: q.getEntriesByCategoryAndTypeStmt,
		getUserByUsernameStmt:           q.getUserByUsernameStmt,
		updateUserNameByUsernameStmt:    q.updateUserNameByUsernameStmt,
	}
}
