// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, hashed_password, full_name, email, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, hashed_password, full_name, email, created_at
`

type CreateUserParams struct {
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashedPassword"`
	FullName       string    `json:"fullName"`
	Email          string    `json:"email"`
	CreatedAt      time.Time `json:"createdAt"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.Username,
		arg.HashedPassword,
		arg.FullName,
		arg.Email,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserByUsername = `-- name: DeleteUserByUsername :exec
DELETE FROM users
WHERE username = $1
`

func (q *Queries) DeleteUserByUsername(ctx context.Context, username string) error {
	_, err := q.exec(ctx, q.deleteUserByUsernameStmt, deleteUserByUsername, username)
	return err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, hashed_password, full_name, email, created_at FROM users 
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.queryRow(ctx, q.getUserByUsernameStmt, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserNameByUsername = `-- name: UpdateUserNameByUsername :exec
UPDATE users SET full_name = $1
WHERE username = $2
`

type UpdateUserNameByUsernameParams struct {
	FullName string `json:"fullName"`
	Username string `json:"username"`
}

func (q *Queries) UpdateUserNameByUsername(ctx context.Context, arg UpdateUserNameByUsernameParams) error {
	_, err := q.exec(ctx, q.updateUserNameByUsernameStmt, updateUserNameByUsername, arg.FullName, arg.Username)
	return err
}
