// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package db

import (
	"context"
	"time"
)

const filterEntriesByDate = `-- name: FilterEntriesByDate :many
SELECT id, account_id, amount, type, category, created_at FROM entries
WHERE account_id = $1 AND created_at >= $2 AND created_at <= $3
ORDER BY created_at DESC
`

type FilterEntriesByDateParams struct {
	AccountID   int64     `json:"accountId"`
	CreatedAt   time.Time `json:"createdAt"`
	CreatedAt_2 time.Time `json:"createdAt2"`
}

func (q *Queries) FilterEntriesByDate(ctx context.Context, arg FilterEntriesByDateParams) ([]Entry, error) {
	rows, err := q.query(ctx, q.filterEntriesByDateStmt, filterEntriesByDate, arg.AccountID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Type,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntriesByAccountId = `-- name: GetEntriesByAccountId :many
SELECT id, account_id, amount, type, category, created_at FROM entries 
WHERE account_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetEntriesByAccountId(ctx context.Context, accountID int64) ([]Entry, error) {
	rows, err := q.query(ctx, q.getEntriesByAccountIdStmt, getEntriesByAccountId, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Type,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntriesByCategoryAndType = `-- name: GetEntriesByCategoryAndType :many
SELECT category, SUM(amount) AS total
FROM entries
WHERE account_id = $1 AND
type = $2
GROUP BY category ORDER BY category DESC
`

type GetEntriesByCategoryAndTypeParams struct {
	AccountID int64  `json:"accountId"`
	Type      string `json:"type"`
}

type GetEntriesByCategoryAndTypeRow struct {
	Category string `json:"category"`
	Total    int64  `json:"total"`
}

func (q *Queries) GetEntriesByCategoryAndType(ctx context.Context, arg GetEntriesByCategoryAndTypeParams) ([]GetEntriesByCategoryAndTypeRow, error) {
	rows, err := q.query(ctx, q.getEntriesByCategoryAndTypeStmt, getEntriesByCategoryAndType, arg.AccountID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntriesByCategoryAndTypeRow
	for rows.Next() {
		var i GetEntriesByCategoryAndTypeRow
		if err := rows.Scan(&i.Category, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
